# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{osdb}
  s.version = "0.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Jean Boussier}]
  s.date = %q{2011-10-11}
  s.email = %q{jean.boussier @nospam@ gmail.com}
  s.executables = [%q{getsub}]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Manifest",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/getsub",
    "lib/osdb.rb",
    "lib/osdb/language.rb",
    "lib/osdb/movie.rb",
    "lib/osdb/server.rb",
    "lib/osdb/sub.rb",
    "osdb.gemspec",
    "spec/fixtures/somemovie.avi",
    "spec/osdb/language_spec.rb",
    "spec/osdb/movie_spec.rb",
    "spec/osdb/server_spec.rb",
    "spec/osdb/sub_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/byroot/ruby-osdb}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{Ruby library to access OSDb services like OpenSubtitles.org}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 1.3"])
    else
      s.add_dependency(%q<rspec>, ["~> 1.3"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 1.3"])
  end
end

